INSERT INTO PLAYERS(USER_ID, COUNTRY) VALUES('oscar', 'England');

INSERT INTO PLAYERS(USER_ID, COUNTRY) VALUES('sachin', 'India');

INSERT INTO PLAYERS(USER_ID, COUNTRY) VALUES('shubham', 'India');

INSERT INTO PLAYERS(USER_ID, COUNTRY) VALUES('imran', 'Pakistan');

INSERT INTO PLAYERS(USER_ID, COUNTRY) VALUES('andrew', 'USA');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(1, 2, TO_DATE('20160101', 'YYYYMMDD'), 'TEST');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(1, 3, TO_DATE('20160201', 'YYYYMMDD'), 'TEST');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(3, 4, TO_DATE('20160301', 'YYYYMMDD'), 'TEST');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(2, 4, TO_DATE('20160201', 'YYYYMMDD'), 'TEST');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(5, 4, TO_DATE('20160101', 'YYYYMMDD'), 'TEST');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(2, 1, TO_DATE('20160101', 'YYYYMMDD'), 'TWENTY_TWENTY');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(2, 3, TO_DATE('20160201', 'YYYYMMDD'), 'TWENTY_TWENTY');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(3, 4, TO_DATE('20160301', 'YYYYMMDD'), 'TWENTY_TWENTY');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(2, 4, TO_DATE('20160201', 'YYYYMMDD'), 'TWENTY_TWENTY');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(4, 5, TO_DATE('20160101', 'YYYYMMDD'), 'TWENTY_TWENTY');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(3, 2, TO_DATE('20160101', 'YYYYMMDD'), 'LIMITED_OVERS');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(3, 5, TO_DATE('20160201', 'YYYYMMDD'), 'LIMITED_OVERS');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(3, 4, TO_DATE('20160301', 'YYYYMMDD'), 'LIMITED_OVERS');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(1, 4, TO_DATE('20160201', 'YYYYMMDD'), 'LIMITED_OVERS');

INSERT INTO GAMES(WINNER_ID, LOSER_ID, GAME_DATE, GAME_TYPE) VALUES(1, 4, TO_DATE('20160101', 'YYYYMMDD'), 'LIMITED_OVERS');